"""Migration updates.

Revision ID: 456559d7b5b2
Revises: 6cbc64acffe8
Create Date: 2024-10-24 18:55:51.312922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '456559d7b5b2'
down_revision = '6cbc64acffe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('total_price',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
